ДЗ 1
hermanfrelikh/2024-2-VK-EDU-Frontend-H-Frelikh pull request #1
Opened 2024-09-18 22:31 UTC by hermanfrelikh

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:
* Написал функции в convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js
* Написал тест в convertBytesToHuman.test.js

2024-09-19 14:55 UTC, nelkor requested changes
Math.floor точно надо исправить, второй комментарий не обязательно.

2024-09-19 14:55 UTC, nelkor commented on convertBytesToHuman.js
> +    return `${Math.floor(size)} ${unitsOfMeasurement[index]}`;
Если ты уже проверил число на Integer, то, кажется, `Math.floor` ему уже не нужен.

2024-09-19 14:55 UTC, nelkor commented on convertBytesToHuman.js
> +      `${size.toFixed(2)}`.replace(/\.?0+$/, "") +
Вообще это делается гораздо проще. Любое число (не важно, целое или дробное) приводишь к `toFixed(2)`, получается строка. Потом читаешь эту строку при помощи `parseFloat`, получается число. И это число вставляешь в финальный рендер строки.

Но это не обязательно. Если хочешь оставить так, то можно и так. Так тоже работает.

2024-09-20 07:08 UTC, nelkor approved these changes

2024-09-21 17:28 UTC, martinkomitsky approved these changes
12!

2024-09-21 17:28 UTC, merged