Homework 2
hermanfrelikh/2024-2-VK-EDU-Frontend-H-Frelikh pull request #2
Opened 2024-09-26 10:26 UTC by hermanfrelikh

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:
* Сделал экран чата приложения Messenger
* Стилизовал форму отправки сообщений
* Сделал так, чтобы по нажатию на кнопку Enter, сообщение сохранялось в localStorage и добавлялось к списку сообщений выше

2024-09-27 09:23 UTC, nelkor requested changes
Первая партия правок. Пока что глубоко не смотрел, надо поправить сначала это.

2024-09-27 09:23 UTC, nelkor commented on 2 homework/simple-chat/.github/workflows/gh-pages.yml
> +      working-directory: ./2 homework/simple-chat
Зачем два `gh-pages.yml` для одного проекта?

2024-09-27 09:23 UTC, nelkor commented on 2 homework/simple-chat/build/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
Этого файла не должно быть в PR. Как и всей этой директории. Добавить в игнор.

2024-09-27 09:23 UTC, nelkor commented on 2 homework/simple-chat/package.json
> +    "build": "webpack --mode=development"
Собираем с флагом `production`.

2024-09-27 09:23 UTC, nelkor commented on 2 homework/simple-chat/package.json
> +    "webpack": "^4.41.0",
Почему такая старая версия?

2024-09-27 09:23 UTC, nelkor commented on 2 homework/simple-chat/src/index.html
> +      <button id="clearStorage">Очистить localStorage</button> <!-- Не является функционалом приложения, сделана, чтобы убирать сообщения при тестах -->
А при сборке приложения эта кнопка как-то убирается?

2024-09-27 09:23 UTC, nelkor commented on 2 homework/simple-chat/src/index.html
> +            src="https://sun9-44.userapi.com/impg/Fmp3R9zTLJnkrYrJgRPPq8IfQ2tClWKByoHv9w/Lj9oGtVjToE.jpg?size=1080x1440&quality=95&sign=7019cbcdb9a7e615206611f82c34838a&type=album"
Раз уж мы тут пользуемся вебпаком, было бы неплохо картинки тоже держать в `src`. И шрифты. Но это уже чуть более продвинутый уровень, так что не обязательно.

2024-10-02 06:56 UTC, nelkor requested changes
Очень плохо, предыдущие замечания не исправлены, плюс добавились новые. Не надо отправлять задание на ревью, пока не исправлены замечания.

2024-10-02 06:56 UTC, nelkor commented on .github/workflows/gh-pages.yml
> +        publish_dir: ./simple-chat/build
Нет конца строки.

2024-10-02 06:56 UTC, nelkor commented on .gitignore
> +
Слишком много концов строки 😅

2024-10-02 06:56 UTC, nelkor commented on 2 homework/simple-chat/.github/workflows/gh-pages.yml
> +      working-directory: ./2 homework/simple-chat
Это не исправлено.

2024-10-02 06:56 UTC, nelkor commented on 2 homework/simple-chat/build/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
Это не исправлено.

2024-10-02 06:56 UTC, nelkor commented on 2 homework/simple-chat/package.json
> +    "build": "webpack --mode=development"
Это не исправлено.

2024-10-02 06:56 UTC, nelkor commented on 2 homework/simple-chat/package.json
> +    "webpack": "^4.41.0",
Это не исправлено.

2024-10-02 06:56 UTC, nelkor commented on 2 homework/simple-chat/src/index.html
> +            src="https://sun9-44.userapi.com/impg/Fmp3R9zTLJnkrYrJgRPPq8IfQ2tClWKByoHv9w/Lj9oGtVjToE.jpg?size=1080x1440&quality=95&sign=7019cbcdb9a7e615206611f82c34838a&type=album"
Это не исправлено.

2024-10-02 06:56 UTC, nelkor commented on 2 homework/simple-chat/src/index.html
> +      <button id="clearStorage">Очистить localStorage</button> <!-- Не является функционалом приложения, сделана, чтобы убирать сообщения при тестах -->
Это не исправлено.

2024-10-02 06:56 UTC, nelkor commented on simple-chat/src/index.html
> +      <!-- <button id="clearStorage">Очистить localStorage</button> Не является функционалом приложения, сделана, чтобы убирать сообщения при тестах -->
Не должно быть закомментированного кода.

2024-10-02 06:56 UTC, nelkor commented on simple-chat/src/index.js
> +  // const clearStorageButton = document.querySelector("#clearStorage");
Тут тоже.

2024-10-02 06:56 UTC, nelkor commented on simple-chat/src/index.js
> +  // clearStorageButton.addEventListener("click", clearStorage);
И тут.

2024-10-02 06:56 UTC, nelkor commented on simple-chat/src/index.js
> +  // }
И даже тут.

2024-10-02 12:28 UTC, nelkor requested changes
Ничего не исправлено)

2024-10-03 13:13 UTC, nelkor requested changes
Нужна ссылка на GitHub Pages.

2024-10-03 13:13 UTC, nelkor commented on .gitignore
> +simple-chat/build/
Вот так сделаешь и папка build будет игнорироваться в любой подпапке.

```suggestion
build
```

2024-10-03 13:27 UTC, nelkor requested changes
Тут только Яна? Надо, чтобы можно было писать от лица разных пользователей и чтобы "свои" сообщения выделялись.

И убери, пожалуйста, горизонтальный скролл.

2024-10-06 11:09 UTC, nelkor requested changes
Кнопка должна быть button, а не span (можно span внутри button).

При смене пользователя внешний вид сообщений тоже должен изменяться. Нужные сообщения должны становиться "твоими".

2024-10-07 17:32 UTC, nelkor approved these changes

2024-10-07 19:47 UTC, merged

2024-10-07 19:47 UTC, martinkomitsky commented
12!